development:
  adapter: mysql2
  database: db_explorer
  username: root
  password:

test:
  adapter: mysql2
  database: db_explorer_test
  username: root
  password:

production:
  adapter: mysql2
  database: db_explorer
  username: root
  password:
